package org.bouncycastle.asn1.u2;

import androidx.exifinterface.media.ExifInterface;
import org.bouncycastle.asn1.m;

/* loaded from: classes4.dex */
public interface p {
    public static final m A2;
    public static final m A3;
    public static final m B2;
    public static final m B3;
    public static final m C2;
    public static final m C3;
    public static final m D2;
    public static final m D3;
    public static final m E2;
    public static final m E3;
    public static final m F2;
    public static final m F3;
    public static final m G2;
    public static final m G3;
    public static final m H2;
    public static final m I2;
    public static final m J2;
    public static final m K2;
    public static final m L2;
    public static final m M2;
    public static final m N2;
    public static final m O2;
    public static final m P2;
    public static final m Q2;
    public static final m R2;
    public static final m S2;
    public static final m T2;
    public static final m U2;
    public static final m V2;
    public static final m W2;
    public static final m X2;
    public static final m Y2;
    public static final m Z2;
    public static final m a3;
    public static final m b3;
    public static final m c3;
    public static final m d3;
    public static final m e3;
    public static final m f3;
    public static final m g3;
    public static final m h3;
    public static final m i3;
    public static final m j3;
    public static final m k3;
    public static final m l3 = new m("1.2.840.10040.4.1");
    public static final m m3 = new m("1.2.840.10040.4.3");
    public static final m n3;
    public static final m o3;
    public static final m q3;
    public static final m r2;
    public static final m r3;
    public static final m s2;
    public static final m s3;
    public static final m t2;
    public static final m t3;
    public static final m u2;
    public static final m u3;
    public static final m v2;
    public static final m v3;
    public static final m w2;
    public static final m w3;
    public static final m x2;
    public static final m x3;
    public static final m y2;
    public static final m y3;
    public static final m z2;
    public static final m z3;

    static {
        m mVar = new m("1.2.840.10045");
        r2 = mVar;
        m m = mVar.m("1");
        s2 = m;
        t2 = m.m("1");
        m m2 = m.m(ExifInterface.GPS_MEASUREMENT_2D);
        u2 = m2;
        v2 = m2.m("3.1");
        w2 = m2.m("3.2");
        x2 = m2.m("3.3");
        m m4 = mVar.m("4");
        y2 = m4;
        z2 = m4.m("1");
        m m5 = mVar.m(ExifInterface.GPS_MEASUREMENT_2D);
        A2 = m5;
        B2 = m5.m("1");
        m m6 = m4.m(ExifInterface.GPS_MEASUREMENT_3D);
        C2 = m6;
        D2 = m6.m("1");
        E2 = m6.m(ExifInterface.GPS_MEASUREMENT_2D);
        F2 = m6.m(ExifInterface.GPS_MEASUREMENT_3D);
        G2 = m6.m("4");
        m m7 = mVar.m(ExifInterface.GPS_MEASUREMENT_3D);
        H2 = m7;
        m m8 = m7.m("0");
        I2 = m8;
        J2 = m8.m("1");
        K2 = m8.m(ExifInterface.GPS_MEASUREMENT_2D);
        L2 = m8.m(ExifInterface.GPS_MEASUREMENT_3D);
        M2 = m8.m("4");
        N2 = m8.m("5");
        O2 = m8.m("6");
        P2 = m8.m("7");
        Q2 = m8.m("8");
        R2 = m8.m("9");
        S2 = m8.m("10");
        T2 = m8.m("11");
        U2 = m8.m("12");
        V2 = m8.m("13");
        W2 = m8.m("14");
        X2 = m8.m("15");
        Y2 = m8.m("16");
        Z2 = m8.m("17");
        a3 = m8.m("18");
        b3 = m8.m("19");
        c3 = m8.m("20");
        m m9 = m7.m("1");
        d3 = m9;
        e3 = m9.m("1");
        f3 = m9.m(ExifInterface.GPS_MEASUREMENT_2D);
        g3 = m9.m(ExifInterface.GPS_MEASUREMENT_3D);
        h3 = m9.m("4");
        i3 = m9.m("5");
        j3 = m9.m("6");
        k3 = m9.m("7");
        m mVar2 = new m("1.3.133.16.840.63.0");
        n3 = mVar2;
        o3 = mVar2.m(ExifInterface.GPS_MEASUREMENT_2D);
        q3 = mVar2.m(ExifInterface.GPS_MEASUREMENT_3D);
        r3 = mVar2.m("16");
        m mVar3 = new m("1.2.840.10046");
        s3 = mVar3;
        t3 = mVar3.m("2.1");
        m m10 = mVar3.m(ExifInterface.GPS_MEASUREMENT_3D);
        u3 = m10;
        v3 = m10.m("1");
        w3 = m10.m(ExifInterface.GPS_MEASUREMENT_2D);
        x3 = m10.m(ExifInterface.GPS_MEASUREMENT_3D);
        y3 = m10.m("4");
        z3 = m10.m("5");
        A3 = m10.m("6");
        B3 = m10.m("7");
        C3 = m10.m("8");
        m mVar4 = new m("1.3.133.16.840.9.44");
        D3 = mVar4;
        m m11 = mVar4.m("1");
        E3 = m11;
        F3 = m11.m("1");
        G3 = m11.m(ExifInterface.GPS_MEASUREMENT_2D);
    }
}
